### ISSUE TITLE
GPL license? 

### ISSUE THREAD

**Issue by johndpope** [Octadero/TensorFlow#1]
do you realize how bad this license is? 
if I include it in my app - I must open source my entire code base or pay license. 
GPL has been described as 
"a cancer that attaches itself in an intellectual property sense to everything it touches"
https://blog.jamesbayley.com/2014/01/17/gpl-living-with-cancer/

**Comment by johndpope** [comment]
<img width="1104" alt="screen shot 2017-10-24 at 3 16 58 pm" src="https://user-images.githubusercontent.com/289994/31963377-6bce510e-b8ce-11e7-9a38-9f7340490485.png">

**Comment by VolodymyrPavliukevych** [comment]
Thank you for your question. Yes, I am aware of this issue. This license will only stay till the first release, after the release the license will be Apache.
